import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as api from './finding-api';
import { findingKeys } from './finding-query-keys';

export function useFindings(organizationId: string | undefined, params: api.FindingListParams) { return useQuery({ queryKey: findingKeys.list(organizationId ?? '', params), queryFn: () => api.getFindings(organizationId!, params), enabled: Boolean(organizationId), placeholderData: (previous) => previous }); }
export function useFindingSummary(organizationId: string | undefined) { return useQuery({ queryKey: findingKeys.summary(organizationId ?? ''), queryFn: () => api.getFindingSummary(organizationId!), enabled: Boolean(organizationId), staleTime: 30_000 }); }
export function useFinding(organizationId: string | undefined, findingId: string | undefined) { return useQuery({ queryKey: findingKeys.detail(organizationId ?? '', findingId ?? ''), queryFn: () => api.getFinding(organizationId!, findingId!), enabled: Boolean(organizationId && findingId) }); }
export function useFindingEvidence(organizationId: string | undefined, findingId: string | undefined) { return useQuery({ queryKey: findingKeys.evidence(organizationId ?? '', findingId ?? ''), queryFn: () => api.getFindingEvidence(organizationId!, findingId!), enabled: Boolean(organizationId && findingId) }); }
export function useFindingValidations(organizationId: string | undefined, findingId: string | undefined) { return useQuery({ queryKey: findingKeys.validations(organizationId ?? '', findingId ?? ''), queryFn: () => api.getFindingValidations(organizationId!, findingId!), enabled: Boolean(organizationId && findingId) }); }
export function useFindingActivity(organizationId: string | undefined, findingId: string | undefined) { return useQuery({ queryKey: findingKeys.activity(organizationId ?? '', findingId ?? ''), queryFn: () => api.getFindingActivity(organizationId!, findingId!), enabled: Boolean(organizationId && findingId) }); }

function useFindingMutation<T, R = api.Finding>(mutationFn: (body: T) => Promise<R>, organizationId: string | undefined, findingId?: string) {
  const client = useQueryClient();
  return useMutation({ mutationFn, onSuccess: () => { if (!organizationId) return; void client.invalidateQueries({ queryKey: findingKeys.lists(organizationId) }); void client.invalidateQueries({ queryKey: findingKeys.summary(organizationId) }); if (findingId) void client.invalidateQueries({ queryKey: findingKeys.detail(organizationId, findingId) }); } });
}
export function useCreateFinding(organizationId: string | undefined) { return useFindingMutation((body: api.CreateFindingInput) => api.createFinding(organizationId!, body), organizationId); }
export function useUpdateFinding(organizationId: string | undefined, findingId: string) { return useFindingMutation((body: api.UpdateFindingInput) => api.updateFinding(organizationId!, findingId, body), organizationId, findingId); }
export function useStartFindingRemediation(organizationId: string | undefined, findingId: string) { return useFindingMutation(() => api.startFindingRemediation(organizationId!, findingId), organizationId, findingId); }
export function useSubmitFindingForValidation(organizationId: string | undefined, findingId: string) { return useFindingMutation(() => api.submitFindingForValidation(organizationId!, findingId), organizationId, findingId); }
export function useReopenFinding(organizationId: string | undefined, findingId: string) { return useFindingMutation((rationale: string) => api.reopenFinding(organizationId!, findingId, rationale), organizationId, findingId); }
export function useCloseFindingExceptionally(organizationId: string | undefined, findingId: string) { return useFindingMutation<{ resolutionType: Exclude<api.FindingResolutionType, 'REMEDIATED'>; resolutionRationale: string }, api.Finding>((body) => api.closeFindingExceptionally(organizationId!, findingId, body), organizationId, findingId); }
export function useValidateFinding(organizationId: string | undefined, findingId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (body: Parameters<typeof api.validateFinding>[2]) => api.validateFinding(organizationId!, findingId, body), onSuccess: () => { if (!organizationId) return; void client.invalidateQueries({ queryKey: findingKeys.lists(organizationId) }); void client.invalidateQueries({ queryKey: findingKeys.summary(organizationId) }); void client.invalidateQueries({ queryKey: findingKeys.detail(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.validations(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.activity(organizationId, findingId) }); } }); }
export function useLinkFindingEvidence(organizationId: string | undefined, findingId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (body: { evidenceVersionId: string; purpose: api.FindingEvidencePurpose }) => api.linkFindingEvidence(organizationId!, findingId, body.evidenceVersionId, body.purpose), onSuccess: () => { if (!organizationId) return; void client.invalidateQueries({ queryKey: findingKeys.evidence(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.detail(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.activity(organizationId, findingId) }); } }); }
export function useUnlinkFindingEvidence(organizationId: string | undefined, findingId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (linkId: string) => api.unlinkFindingEvidence(organizationId!, findingId, linkId), onSuccess: () => { if (!organizationId) return; void client.invalidateQueries({ queryKey: findingKeys.evidence(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.detail(organizationId, findingId) }); void client.invalidateQueries({ queryKey: findingKeys.activity(organizationId, findingId) }); } }); }
export function usePromoteObservationToFinding(organizationId: string | undefined, auditTestId: string, observationId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (body: api.PromoteFindingInput) => api.promoteObservationToFinding(organizationId!, auditTestId, observationId, body), onSuccess: () => { if (!organizationId) return; void client.invalidateQueries({ queryKey: findingKeys.lists(organizationId) }); void client.invalidateQueries({ queryKey: findingKeys.summary(organizationId) }); void client.invalidateQueries({ queryKey: ['audit-test-observations', organizationId, auditTestId] }); } }); }
