import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';

import type { OrganizationAccess } from '../../common/auth/auth.types';
// Nest uses the runtime constructor token for dependency injection.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { OrganizationAuthorizationService } from '../../common/authorization';
// Nest uses the runtime constructor token for dependency injection.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { PrismaService } from '../../database/prisma.service';
import type { AssignOrganizationUnitMemberDto, ListOrganizationUnitsDto, OrganizationUnitDto, UpdateOrganizationUnitDto } from './dto';

@Injectable()
export class OrganizationUnitsService {
  constructor(private readonly prisma: PrismaService, private readonly authorization: OrganizationAuthorizationService) {}
  private organizationId(access: OrganizationAccess) { return access.organization.id; }
  private assertManage(access: OrganizationAccess) { if (!this.authorization.canManageOrganization(access.roleCodes)) throw new ForbiddenException('Not allowed to manage organization units'); }
  private async assertParent(tx: Prisma.TransactionClient | PrismaService, organizationId: string, unitId: string | null | undefined) { if (!unitId) return; const parent = await tx.organizationUnit.findFirst({ where: { organizationId, id: unitId }, select: { id: true } }); if (!parent) throw new NotFoundException('Organization unit parent not found'); }
  private async assertNoCycle(tx: Prisma.TransactionClient | PrismaService, organizationId: string, unitId: string, parentId: string | null | undefined) { if (!parentId) return; if (unitId === parentId) throw new ConflictException('ORGANIZATION_UNIT_CIRCULAR_PARENT'); const seen = new Set<string>(); let cursor: string | null = parentId; while (cursor) { if (seen.has(cursor) || cursor === unitId) throw new ConflictException('ORGANIZATION_UNIT_CIRCULAR_PARENT'); seen.add(cursor); const parent: { parentId: string | null } | null = await tx.organizationUnit.findFirst({ where: { organizationId, id: cursor }, select: { parentId: true } }); if (!parent) throw new NotFoundException('Organization unit parent not found'); cursor = parent.parentId; } }

  async list(access: OrganizationAccess, dto: ListOrganizationUnitsDto) { const organizationId = this.organizationId(access); const where: Prisma.OrganizationUnitWhereInput = { organizationId, ...(dto.parentId !== undefined ? { parentId: dto.parentId } : {}), ...(dto.isActive !== undefined ? { isActive: dto.isActive } : {}), ...(dto.search ? { OR: [{ name: { contains: dto.search, mode: 'insensitive' } }, { code: { contains: dto.search, mode: 'insensitive' } }] } : {}) }; const units = await this.prisma.organizationUnit.findMany({ where, include: { _count: { select: { children: true, members: true } } }, orderBy: [{ name: 'asc' }] }); return { data: units.map((unit) => this.present(unit)) }; }
  async findOne(access: OrganizationAccess, unitId: string) { const unit = await this.prisma.organizationUnit.findFirst({ where: { organizationId: this.organizationId(access), id: unitId }, include: { _count: { select: { children: true, members: true } }, parent: { select: { id: true, name: true, code: true } } } }); if (!unit) throw new NotFoundException('Organization unit not found'); return this.present(unit); }
  async create(access: OrganizationAccess, dto: OrganizationUnitDto) { this.assertManage(access); const organizationId = this.organizationId(access); try { return await this.prisma.$transaction(async (tx) => { await this.assertParent(tx, organizationId, dto.parentId); const unit = await tx.organizationUnit.create({ data: { organizationId, name: dto.name.trim(), code: dto.code?.trim() || null, description: dto.description?.trim() || null, parentId: dto.parentId ?? null }, include: { _count: { select: { children: true, members: true } } } }); return this.present(unit); }); } catch (error) { if (this.isUnique(error)) throw new ConflictException('ORGANIZATION_UNIT_ALREADY_EXISTS'); throw error; } }
  async update(access: OrganizationAccess, unitId: string, dto: UpdateOrganizationUnitDto) { this.assertManage(access); const organizationId = this.organizationId(access); try { return await this.prisma.$transaction(async (tx) => { const current = await tx.organizationUnit.findFirst({ where: { organizationId, id: unitId }, select: { id: true } }); if (!current) throw new NotFoundException('Organization unit not found'); await this.assertParent(tx, organizationId, dto.parentId); await this.assertNoCycle(tx, organizationId, unitId, dto.parentId); const unit = await tx.organizationUnit.update({ where: { organizationId_id: { organizationId, id: unitId } }, data: { ...(dto.name !== undefined ? { name: dto.name.trim() } : {}), ...(dto.code !== undefined ? { code: dto.code?.trim() || null } : {}), ...(dto.description !== undefined ? { description: dto.description?.trim() || null } : {}), ...(dto.parentId !== undefined ? { parentId: dto.parentId } : {}), ...(dto.isActive !== undefined ? { isActive: dto.isActive } : {}) }, include: { _count: { select: { children: true, members: true } } } }); return this.present(unit); }); } catch (error) { if (this.isUnique(error)) throw new ConflictException('ORGANIZATION_UNIT_ALREADY_EXISTS'); throw error; } }
  async deactivate(access: OrganizationAccess, unitId: string) { this.assertManage(access); const organizationId = this.organizationId(access); const unit = await this.prisma.organizationUnit.findFirst({ where: { organizationId, id: unitId }, select: { id: true } }); if (!unit) throw new NotFoundException('Organization unit not found'); const children = await this.prisma.organizationUnit.count({ where: { organizationId, parentId: unitId } }); if (children) throw new ConflictException('ORGANIZATION_UNIT_HAS_CHILDREN'); return this.prisma.organizationUnit.update({ where: { organizationId_id: { organizationId, id: unitId } }, data: { isActive: false } }); }
  async members(access: OrganizationAccess, unitId: string) { const organizationId = this.organizationId(access); await this.assertUnit(organizationId, unitId); const data = await this.prisma.organizationUnitMember.findMany({ where: { organizationId, organizationUnitId: unitId }, include: { membership: { include: { user: { select: { id: true, email: true } }, membershipRoles: { include: { role: true } } } } }, orderBy: { createdAt: 'asc' } }); return { data: data.map((item) => ({ membershipId: item.membershipId, email: item.membership.user.email, status: item.membership.status, roles: item.membership.membershipRoles.map((role) => ({ code: role.role.code, name: role.role.name })) })) }; }
  async addMember(access: OrganizationAccess, unitId: string, dto: AssignOrganizationUnitMemberDto) { this.assertManage(access); const organizationId = this.organizationId(access); await this.assertUnit(organizationId, unitId); const membership = await this.prisma.membership.findFirst({ where: { organizationId, id: dto.membershipId, status: 'ACTIVE' }, select: { id: true } }); if (!membership) throw new NotFoundException('Active organization membership not found'); try { return await this.prisma.organizationUnitMember.create({ data: { organizationId, organizationUnitId: unitId, membershipId: dto.membershipId } }); } catch (error) { if (this.isUnique(error)) throw new ConflictException('ORGANIZATION_UNIT_MEMBER_ALREADY_EXISTS'); throw error; } }
  async removeMember(access: OrganizationAccess, unitId: string, membershipId: string) { this.assertManage(access); const organizationId = this.organizationId(access); const assignment = await this.prisma.organizationUnitMember.findFirst({ where: { organizationId, organizationUnitId: unitId, membershipId } }); if (!assignment) throw new NotFoundException('Organization unit member assignment not found'); await this.prisma.organizationUnitMember.delete({ where: { organizationId_organizationUnitId_membershipId: { organizationId, organizationUnitId: unitId, membershipId } } }); return { deleted: true }; }
  private async assertUnit(organizationId: string, unitId: string) { const unit = await this.prisma.organizationUnit.findFirst({ where: { organizationId, id: unitId }, select: { id: true } }); if (!unit) throw new NotFoundException('Organization unit not found'); }
  private present(unit: any) { return { id: unit.id, organizationId: unit.organizationId, name: unit.name, code: unit.code, description: unit.description, parentId: unit.parentId, parent: unit.parent ?? null, isActive: unit.isActive, createdAt: unit.createdAt, updatedAt: unit.updatedAt, counts: { children: unit._count?.children ?? 0, members: unit._count?.members ?? 0 } }; }
  private isUnique(error: unknown) { return error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002'; }
}
