"use client"

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react"
import { useQuery } from "@tanstack/react-query"
import { CalendarDays, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { MorphNativeSelect } from "@/components/ui/morph-select"
import { Sheet, SheetContent, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { getControls } from "@/features/controls/control-api"
import { adoptComplianceFramework, createRequirementAssessment, getFrameworkCatalog, linkRequirementControl, updateRequirement, type ComplianceFramework, type ComplianceRequirement, type ComplianceRequirementStatus, type LinkedControl } from "./compliance-api"
import { statusLabel } from "./compliance-format"

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2"><span className="text-xs font-medium text-text-secondary">{label}</span>{children}</label> }
function ErrorText({ error }: { error: unknown }) { return error ? <p className="text-sm text-danger">{error instanceof Error ? error.message : "Unable to save changes."}</p> : null }

export function AdoptFrameworkSheet({ organizationId, membershipId, open, onOpenChange, onAdopted }: { organizationId: string; membershipId: string; open: boolean; onOpenChange: (open: boolean) => void; onAdopted: (framework: ComplianceFramework) => void }) { const catalogQuery = useQuery({ queryKey: ["framework-catalog"], queryFn: getFrameworkCatalog, enabled: open, staleTime: 300_000 }); const [catalogId, setCatalogId] = useState(""); const [targetDate, setTargetDate] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null); useEffect(() => { const first = catalogQuery.data?.frameworks[0]; if (!catalogId && first) setCatalogId(first.id) }, [catalogId, catalogQuery.data]); async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const framework = await adoptComplianceFramework(organizationId, { frameworkCatalogId: catalogId, ...(membershipId ? { ownerMembershipId: membershipId } : {}), ...(targetDate ? { targetDate: new Date(`${targetDate}T00:00:00`).toISOString() } : {}) }); onAdopted(framework); onOpenChange(false) } catch (caught) { setError(caught) } finally { setSaving(false) } } return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">Adopt framework</SheetTitle><p className="text-sm text-text-muted">Start tracking requirements from the framework catalog.</p></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Framework"><MorphNativeSelect value={catalogId} onChange={setCatalogId} className="w-full">{catalogQuery.data?.frameworks.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.name} · {item.version}</option>)}</MorphNativeSelect></Field><Field label="Owner"><MorphNativeSelect value={membershipId} onChange={() => undefined} disabled className="w-full"><option value={membershipId}>You</option></MorphNativeSelect></Field><Field label="Target date"><div className="relative"><Input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /><CalendarDays className="pointer-events-none absolute right-3 top-2 size-4 text-text-muted" /></div></Field><ErrorText error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving || !catalogId}>{saving ? <Loader2 className="animate-spin" /> : null}Adopt framework</Button></SheetFooter></form></SheetContent></Sheet> }

export function EditRequirementSheet({ organizationId, requirement, membershipId, open, onOpenChange, onSaved }: { organizationId: string; requirement: ComplianceRequirement; membershipId: string; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) { const [owner, setOwner] = useState(requirement.owner?.id ?? ""); const [notes, setNotes] = useState(requirement.notes ?? ""); const [targetDate, setTargetDate] = useState(requirement.targetDate?.slice(0, 10) ?? ""); const [nextReviewAt, setNextReviewAt] = useState(requirement.nextReviewAt?.slice(0, 10) ?? ""); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null); useEffect(() => { if (open) { setOwner(requirement.owner?.id ?? ""); setNotes(requirement.notes ?? ""); setTargetDate(requirement.targetDate?.slice(0, 10) ?? ""); setNextReviewAt(requirement.nextReviewAt?.slice(0, 10) ?? "") } }, [open, requirement]); async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await updateRequirement(organizationId, requirement.id, { ownerMembershipId: owner || null, notes: notes || null, targetDate: targetDate ? new Date(`${targetDate}T00:00:00`).toISOString() : null, nextReviewAt: nextReviewAt ? new Date(`${nextReviewAt}T00:00:00`).toISOString() : null }); onSaved(); onOpenChange(false) } catch (caught) { setError(caught) } finally { setSaving(false) } } return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">Edit requirement</SheetTitle></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Owner"><MorphNativeSelect value={owner} onChange={setOwner} className="w-full"><option value="">Unassigned</option><option value={membershipId}>You</option></MorphNativeSelect></Field><Field label="Target date"><Input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /></Field><Field label="Next review"><Input type="date" value={nextReviewAt} onChange={(event) => setNextReviewAt(event.target.value)} /></Field><Field label="Notes"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} className="min-h-32" /></Field><ErrorText error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Save changes</Button></SheetFooter></form></SheetContent></Sheet> }

export function AssessmentDialog({ organizationId, requirementId, open, onOpenChange, onSaved }: { organizationId: string; requirementId: string; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) { const [status, setStatus] = useState<ComplianceRequirementStatus>("COMPLIANT"); const [rationale, setRationale] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null); async function submit(event: FormEvent) { event.preventDefault(); if (status === "NOT_APPLICABLE" && !rationale.trim()) { setError(new Error("A rationale is required when a requirement is not applicable.")); return } setSaving(true); setError(null); try { await createRequirementAssessment(organizationId, requirementId, { status, rationale }); onSaved(); onOpenChange(false); setRationale("") } catch (caught) { setError(caught) } finally { setSaving(false) } } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Assess requirement</DialogTitle><DialogDescription>Record an immutable assessment for the current requirement state.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><Field label="Status"><MorphNativeSelect value={status} onChange={(value) => setStatus(value as ComplianceRequirementStatus)} className="w-full">{Object.entries(statusLabel).filter(([key]) => key !== "NOT_ASSESSED").map(([key, label]) => <option key={key} value={key}>{label}</option>)}</MorphNativeSelect></Field><Field label="Rationale"><Textarea value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder="Describe the current state and supporting rationale." className="min-h-28" /></Field><ErrorText error={error} /><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save assessment"}</Button></DialogFooter></form></DialogContent></Dialog> }

export function LinkControlDialog({ organizationId, requirementId, linkedControls, open, onOpenChange, onLinked }: { organizationId: string; requirementId: string; linkedControls: LinkedControl[]; open: boolean; onOpenChange: (open: boolean) => void; onLinked: () => void }) { const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null); const controlsQuery = useQuery({ queryKey: ["compliance-control-search", organizationId, search], queryFn: () => getControls(organizationId, { search, page: 1, pageSize: 20 }), enabled: open }); const linkedIds = useMemo(() => new Set(linkedControls.map((control) => control.id)), [linkedControls]); const available = (controlsQuery.data?.data ?? []).filter((control) => !linkedIds.has(control.id) && control.status !== "ARCHIVED"); async function submit() { if (!selected) return; setSaving(true); setError(null); try { await linkRequirementControl(organizationId, requirementId, selected); onLinked(); onOpenChange(false); setSelected(null); setSearch("") } catch (caught) { setError(caught) } finally { setSaving(false) } } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Link control</DialogTitle><DialogDescription>Choose an existing control that implements this requirement.</DialogDescription></DialogHeader><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search controls..." />{available.length ? <div className="max-h-64 overflow-y-auto divide-y divide-border-subtle border-y border-border-subtle">{available.map((control) => <button type="button" key={control.id} onClick={() => setSelected(control.id)} className={`flex w-full items-center gap-3 py-3 text-left ${selected === control.id ? "text-text-primary" : "text-text-secondary"}`}><span className={`size-4 rounded-full border ${selected === control.id ? "border-primary bg-primary" : "border-border-strong"}`} /><span><span className="block text-xs text-text-muted">{control.code}</span><span className="text-sm">{control.title}</span></span></button>)}</div> : <p className="py-5 text-sm text-text-muted">No unlinked controls found.</p>}<ErrorText error={error} /><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={!selected || saving}>{saving ? "Linking..." : "Link control"}</Button></DialogFooter></DialogContent></Dialog> }
