"use client"

import * as React from "react"
import { useEffect, useState } from "react"
import { CalendarDays, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { MorphSelect, MorphSelectContent, MorphSelectItem as SelectItem, MorphSelectTrigger, MorphSelectValue } from "@/components/ui/morph-select"
import { Sheet, SheetContent, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Textarea } from "@/components/ui/textarea"
import { createControl, createControlExecution, updateControl, type Control, type ControlAutomationType, type ControlFrequency, type ControlType } from "./control-api"
import { automationLabel, frequencyLabel, typeLabel } from "./control-format"

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-text-secondary">{label}</Label>{children}</div> }
function FormError({ error }: { error: string | null }) { return error ? <p className="text-sm text-danger">{error}</p> : null }
function ErrorMessage(error: unknown) { return error instanceof Error ? error.message : "Something went wrong. Please try again." }
function SelectField({ label, value, onValueChange, children }: { label: string; value: string; onValueChange: (value: string) => void; children: React.ReactNode }) { return <Field label={label}><MorphSelect value={value} onValueChange={(next) => next && onValueChange(next)}><MorphSelectTrigger className="w-full"><MorphSelectValue /></MorphSelectTrigger><MorphSelectContent>{children}</MorphSelectContent></MorphSelect></Field> }

const controlTypes: ControlType[] = ["PREVENTIVE", "DETECTIVE", "CORRECTIVE"]
const automationTypes: ControlAutomationType[] = ["MANUAL", "AUTOMATED", "HYBRID"]
const frequencies: ControlFrequency[] = ["CONTINUOUS", "DAILY", "WEEKLY", "MONTHLY", "QUARTERLY", "SEMI_ANNUAL", "ANNUAL", "AD_HOC"]

export function ControlSheet({ organizationId, membershipId, control, open, onOpenChange, onSaved }: { organizationId: string; membershipId: string; control?: Control; open: boolean; onOpenChange: (open: boolean) => void; onSaved: (control: Control) => void }) {
  const editing = Boolean(control); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState(""); const [type, setType] = useState<ControlType>("DETECTIVE"); const [automationType, setAutomationType] = useState<ControlAutomationType>("MANUAL"); const [frequency, setFrequency] = useState<ControlFrequency>("QUARTERLY"); const [owner, setOwner] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!open) return; setTitle(control?.title ?? ""); setDescription(control?.description ?? ""); setCategory(control?.category ?? ""); setType(control?.type ?? "DETECTIVE"); setAutomationType(control?.automationType ?? "MANUAL"); setFrequency(control?.frequency ?? "QUARTERLY"); setOwner(control?.owner?.id ?? "") ; setError(null) }, [control, open])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const body = { title, ...(description ? { description } : {}), ...(category ? { category } : {}), type, automationType, frequency, ...(owner ? { ownerMembershipId: owner } : {}) }; const saved = editing ? await updateControl(organizationId, control!.id, body) : await createControl(organizationId, body); onSaved(saved); onOpenChange(false) } catch (caught) { setError(ErrorMessage(caught)) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">{editing ? "Edit control" : "New control"}</SheetTitle><p className="text-sm text-text-muted">{editing ? "Keep the control definition current." : "Define the safeguard first. Executions can follow from its detail page."}</p></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Control name"><Input required minLength={2} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Privileged Access Review" /></Field><Field label="Description"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what this control is intended to safeguard" className="min-h-28" /></Field><Field label="Category"><Input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. Access Management" /></Field><SelectField label="Control type" value={type} onValueChange={(value) => setType(value as ControlType)}>{controlTypes.map((item) => <SelectItem key={item} value={item}>{typeLabel[item]}</SelectItem>)}</SelectField><SelectField label="Automation" value={automationType} onValueChange={(value) => setAutomationType(value as ControlAutomationType)}>{automationTypes.map((item) => <SelectItem key={item} value={item}>{automationLabel[item]}</SelectItem>)}</SelectField><SelectField label="Frequency" value={frequency} onValueChange={(value) => setFrequency(value as ControlFrequency)}>{frequencies.map((item) => <SelectItem key={item} value={item}>{frequencyLabel[item]}</SelectItem>)}</SelectField><SelectField label="Owner" value={owner || "UNASSIGNED"} onValueChange={(value) => setOwner(value === "UNASSIGNED" ? "" : value)}><SelectItem value="UNASSIGNED">Unassigned</SelectItem><SelectItem value={membershipId}>You</SelectItem></SelectField><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}{editing ? "Save changes" : "Create control"}</Button></SheetFooter></form></SheetContent></Sheet>
}

export function ExecutionSheet({ organizationId, controlId, membershipId, open, onOpenChange, onSaved }: { organizationId: string; controlId: string; membershipId: string; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const [periodLabel, setPeriodLabel] = useState(""); const [periodStart, setPeriodStart] = useState(""); const [periodEnd, setPeriodEnd] = useState(""); const [dueAt, setDueAt] = useState(""); const [assignee, setAssignee] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (open) { setPeriodLabel(""); setPeriodStart(""); setPeriodEnd(""); setDueAt(""); setAssignee(""); setError(null) } }, [open])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await createControlExecution(organizationId, controlId, { periodLabel, periodStart: new Date(`${periodStart}T00:00:00.000Z`).toISOString(), periodEnd: new Date(`${periodEnd}T23:59:59.000Z`).toISOString(), dueAt: new Date(`${dueAt}T23:59:59.000Z`).toISOString(), ...(assignee ? { assignedToMembershipId: assignee } : {}) }); onSaved(); onOpenChange(false) } catch (caught) { setError(ErrorMessage(caught)) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">New execution</SheetTitle><p className="text-sm text-text-muted">Track one occurrence of this control over time.</p></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Period label"><Input required value={periodLabel} onChange={(event) => setPeriodLabel(event.target.value)} placeholder="e.g. Q3 2026" /></Field><Field label="Period start"><div className="relative"><Input required type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /><CalendarDays className="pointer-events-none absolute right-3 top-2 size-4 text-text-muted" /></div></Field><Field label="Period end"><Input required type="date" value={periodEnd} onChange={(event) => setPeriodEnd(event.target.value)} /></Field><Field label="Due date"><Input required type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></Field><SelectField label="Assignee" value={assignee || "UNASSIGNED"} onValueChange={(value) => setAssignee(value === "UNASSIGNED" ? "" : value)}><SelectItem value="UNASSIGNED">Unassigned</SelectItem><SelectItem value={membershipId}>You</SelectItem></SelectField><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Create execution</Button></SheetFooter></form></SheetContent></Sheet>
}

export function CompleteExecutionDialog({ open, onOpenChange, onComplete }: { open: boolean; onOpenChange: (open: boolean) => void; onComplete: (notes: string) => Promise<void> }) { const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await onComplete(notes); onOpenChange(false) } catch (caught) { setError(ErrorMessage(caught)) } finally { setSaving(false) } } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Complete execution</DialogTitle><DialogDescription>Record the completion notes for this occurrence.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Completion notes"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} className="min-h-28" placeholder="Describe what was completed" /></Field><FormError error={error} /><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Complete</Button></DialogFooter></form></DialogContent></Dialog> }
