import { Activity, ArrowRight, CalendarClock } from "lucide-react"
import Link from "next/link"
import type { ControlSummary } from "./control-api"

export function ControlWorkspaceOverview({ summary, isLoading, isError }: { summary: ControlSummary | undefined; isLoading: boolean; isError: boolean }) {
  if (isLoading) return <div className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="h-48 animate-pulse rounded-2xl border border-border-subtle/70 bg-bg-card/45" /><div className="h-48 animate-pulse rounded-2xl border border-border-subtle/70 bg-bg-card/45" /></div>
  if (isError || !summary) return <p className="rounded-xl border border-danger/30 bg-danger-muted/20 px-4 py-3 text-sm text-danger">Unable to load control operations. The register remains available below.</p>
  return <div className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-border-subtle/70 bg-bg-card/45 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-text-muted">Operations health</p><h2 className="mt-2 font-heading text-2xl text-text-primary">Keep the control loop moving</h2><p className="mt-1 text-sm text-text-muted">Live execution posture across all controls.</p></div><Activity className="size-5 text-primary" /></div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><Metric label="Active" value={summary.active} /><Metric label="Overdue" value={summary.overdueExecutions} tone="danger" /><Metric label="Due soon" value={summary.dueSoon} tone="warning" /><Metric label="Unscheduled" value={summary.unscheduled} /></div><div className="mt-6 flex items-center justify-between border-t border-border-subtle/70 pt-4 text-sm"><span className="text-text-muted">Open executions</span><span className="font-medium text-text-primary">{summary.openExecutions}</span></div></section><section className="rounded-2xl border border-border-subtle/70 bg-bg-card/45 p-5 sm:p-6"><div className="flex items-center gap-3"><CalendarClock className="size-5 text-warning" /><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-text-muted">Upcoming operations</p><h2 className="mt-1 font-heading text-xl text-text-primary">Work that needs attention</h2></div></div>{summary.attention.length ? <div className="mt-5 divide-y divide-border-subtle/70">{summary.attention.map((item) => <Link key={item.id} href={`/controls/${item.controlId}`} className="group flex items-center justify-between gap-3 py-3 first:pt-0"><span className="min-w-0"><span className="block truncate text-sm font-medium text-text-primary">{item.code} · {item.title}</span><span className="mt-1 block text-xs text-text-muted">{item.periodLabel} · {item.reason}</span></span><ArrowRight className="size-4 shrink-0 text-text-disabled transition-transform group-hover:translate-x-0.5 group-hover:text-text-primary" /></Link>)}</div> : <p className="mt-5 text-sm text-text-muted">No upcoming control work needs attention.</p>}</section></div>
}

function Metric({ label, value, tone }: { label: string; value: number; tone?: "danger" | "warning" }) { return <div><p className="text-xs text-text-muted">{label}</p><p className={`mt-1 font-heading text-2xl ${tone === "danger" ? "text-danger" : tone === "warning" ? "text-warning" : "text-text-primary"}`}>{value}</p></div> }
