import { AlertTriangle, ArrowRight, ShieldAlert } from "lucide-react"
import Link from "next/link"
import type { ReactNode } from "react"
import type { RiskSummary } from "./risk-api"

export function RiskWorkspaceOverview({ summary, isLoading, isError }: { summary: RiskSummary | undefined; isLoading: boolean; isError: boolean }) {
  if (isLoading) return <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="h-48 animate-pulse rounded-2xl border border-border-subtle/70 bg-bg-card/45" /><div className="h-48 animate-pulse rounded-2xl border border-border-subtle/70 bg-bg-card/45" /></div>
  if (isError || !summary) return <p className="rounded-xl border border-danger/30 bg-danger-muted/20 px-4 py-3 text-sm text-danger">Unable to load risk posture. The register remains available below.</p>
  const distribution = summary.severityDistribution
  return <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-border-subtle/70 bg-bg-card/45 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-text-muted">Risk posture</p><h2 className="mt-2 font-heading text-2xl text-text-primary">Exposure that needs a decision</h2><p className="mt-1 text-sm text-text-muted">Organization-wide signals across the full risk register.</p></div><ShieldAlert className="size-5 text-risk-high" /></div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><PostureMetric label="Active" value={summary.active} /><PostureMetric label="High / critical" value={summary.criticalHigh} tone="danger" /><PostureMetric label="No treatment" value={summary.withoutTreatment} tone="warning" /><PostureMetric label="Review due" value={summary.dueForReview} /></div><div className="mt-6"><div className="flex items-center justify-between text-xs text-text-muted"><span>Assessed severity</span><span>{summary.total - summary.withoutAssessment} of {summary.total} assessed</span></div><div className="mt-2 flex h-2 overflow-hidden rounded-full bg-bg-elevated"><span className="bg-risk-low" style={{ width: `${barWidth(distribution.LOW, summary.total)}%` }} /><span className="bg-risk-medium" style={{ width: `${barWidth(distribution.MEDIUM, summary.total)}%` }} /><span className="bg-risk-high" style={{ width: `${barWidth(distribution.HIGH, summary.total)}%` }} /><span className="bg-risk-critical" style={{ width: `${barWidth(distribution.CRITICAL, summary.total)}%` }} /></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-text-muted"><span>Low {distribution.LOW}</span><span>Medium {distribution.MEDIUM}</span><span>High {distribution.HIGH}</span><span>Critical {distribution.CRITICAL}</span><span>Unrated {distribution.UNRATED}</span></div></div></section><AttentionPanel title="Risk attention" icon={<AlertTriangle className="size-5 text-warning" />} empty="No immediate risk attention items." items={summary.attention.map((item) => ({ id: item.id, href: `/risks/${item.id}`, label: `${item.code} · ${item.title}`, reason: item.reason }))} /></div>
}

function PostureMetric({ label, value, tone }: { label: string; value: number; tone?: "danger" | "warning" }) { return <div><p className="text-xs text-text-muted">{label}</p><p className={`mt-1 font-heading text-2xl ${tone === "danger" ? "text-danger" : tone === "warning" ? "text-warning" : "text-text-primary"}`}>{value}</p></div> }
function barWidth(value: number, total: number) { return total ? Math.round((value / total) * 100) : 0 }
function AttentionPanel({ title, icon, empty, items }: { title: string; icon: ReactNode; empty: string; items: Array<{ id: string; href: string; label: string; reason: string }> }) { return <section className="rounded-2xl border border-border-subtle/70 bg-bg-card/45 p-5 sm:p-6"><div className="flex items-center gap-3"><span>{icon}</span><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-text-muted">Attention queue</p><h2 className="mt-1 font-heading text-xl text-text-primary">{title}</h2></div></div>{items.length ? <div className="mt-5 divide-y divide-border-subtle/70">{items.map((item) => <Link key={item.id} href={item.href} className="group flex items-center justify-between gap-3 py-3 first:pt-0"><span className="min-w-0"><span className="block truncate text-sm font-medium text-text-primary">{item.label}</span><span className="mt-1 block text-xs text-text-muted">{item.reason}</span></span><ArrowRight className="size-4 shrink-0 text-text-disabled transition-transform group-hover:translate-x-0.5 group-hover:text-text-primary" /></Link>)}</div> : <p className="mt-5 text-sm text-text-muted">{empty}</p>}</section> }
