"use client"

import * as React from "react"
import { useEffect, useState, type ReactNode } from "react"
import { CalendarDays, Check, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Sheet, SheetContent, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import type { AssessmentType, Risk, TreatmentStatus, TreatmentStrategy } from "./risk-api"
import { createAssessment, createRisk, updateRisk, updateTreatment } from "./risk-api"
import { severityForScore, strategyLabel, treatmentStatusLabel } from "./risk-format"

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2"><span className="text-xs font-medium text-text-secondary">{label}</span>{children}</label> }
function SelectField({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: ReactNode }) { return <Field label={label}><select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 w-full rounded-lg border border-input bg-bg-card px-3 text-sm text-text-primary outline-none focus:border-border-strong focus:ring-2 focus:ring-primary/20">{children}</select></Field> }
function FormError({ error }: { error: unknown }) { return error ? <p className="text-sm text-danger">{error instanceof Error ? error.message : "Unable to save changes"}</p> : null }

export function CreateRiskSheet({ organizationId, ownerMembershipId, open, onOpenChange, onCreated }: { organizationId: string; ownerMembershipId: string; open: boolean; onOpenChange: (open: boolean) => void; onCreated: (risk: Risk) => void }) {
  const [title, setTitle] = useState("")
  const [description, setDescription] = useState("")
  const [category, setCategory] = useState("")
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<unknown>(null)
  useEffect(() => { if (open) { setTitle(""); setDescription(""); setCategory(""); setError(null) } }, [open])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const risk = await createRisk(organizationId, { title, description, category, ownerMembershipId }); onCreated(risk); onOpenChange(false) } catch (cause) { setError(cause) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">New risk</SheetTitle><p className="text-sm text-text-muted">Create a register entry first. Assessment and treatment can follow from its detail page.</p></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Risk title"><Input required minLength={2} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Privileged access misuse" /></Field><Field label="Description"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe the risk and its potential impact" className="min-h-28" /></Field><Field label="Category"><Input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. Security" /></Field><Field label="Owner"><div className="flex h-9 items-center gap-2 rounded-lg border border-input bg-bg-card px-3 text-sm text-text-secondary"><Check className="size-4 text-primary" />You</div><p className="text-xs text-text-muted">The current membership is used because the backend has no member directory endpoint yet.</p></Field><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Create risk</Button></SheetFooter></form></SheetContent></Sheet>
}

export function EditRiskSheet({ organizationId, risk, open, onOpenChange, onSaved }: { organizationId: string; risk: Risk; open: boolean; onOpenChange: (open: boolean) => void; onSaved: (risk: Risk) => void }) {
  const [title, setTitle] = useState(risk.title); const [description, setDescription] = useState(risk.description ?? ""); const [category, setCategory] = useState(risk.category ?? ""); const [status, setStatus] = useState<"DRAFT" | "ACTIVE">(risk.status === "ACTIVE" ? "ACTIVE" : "DRAFT"); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null)
  useEffect(() => { if (open) { setTitle(risk.title); setDescription(risk.description ?? ""); setCategory(risk.category ?? ""); setStatus(risk.status === "ACTIVE" ? "ACTIVE" : "DRAFT"); setError(null) } }, [open, risk])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const updated = await updateRisk(organizationId, risk.id, { title, description, category, status }); onSaved(updated); onOpenChange(false) } catch (cause) { setError(cause) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">Edit risk</SheetTitle></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><Field label="Risk title"><Input required minLength={2} value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Description"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} className="min-h-28" /></Field><Field label="Category"><Input value={category} onChange={(event) => setCategory(event.target.value)} /></Field><SelectField label="Status" value={status} onChange={(value) => setStatus(value as "DRAFT" | "ACTIVE")}><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option></SelectField><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Save changes</Button></SheetFooter></form></SheetContent></Sheet>
}

export function AssessmentSheet({ organizationId, riskId, open, onOpenChange, onCreated }: { organizationId: string; riskId: string; open: boolean; onOpenChange: (open: boolean) => void; onCreated: () => void }) {
  const [type, setType] = useState<AssessmentType>("RESIDUAL"); const [likelihood, setLikelihood] = useState(3); const [impact, setImpact] = useState(3); const [rationale, setRationale] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null); const score = likelihood * impact; const severity = severityForScore(score)
  useEffect(() => { if (open) { setType("RESIDUAL"); setLikelihood(3); setImpact(3); setRationale(""); setError(null) } }, [open])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await createAssessment(organizationId, riskId, { type, likelihood, impact, rationale }); onCreated(); onOpenChange(false) } catch (cause) { setError(cause) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">New assessment</SheetTitle><p className="text-sm text-text-muted">The server calculates the authoritative score and severity.</p></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><SelectField label="Assessment type" value={type} onChange={(value) => setType(value as AssessmentType)}><option value="INHERENT">Inherent</option><option value="RESIDUAL">Residual</option></SelectField><div className="grid grid-cols-2 gap-4"><SelectField label="Likelihood" value={String(likelihood)} onChange={(value) => setLikelihood(Number(value))}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} / 5</option>)}</SelectField><SelectField label="Impact" value={String(impact)} onChange={(value) => setImpact(Number(value))}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} / 5</option>)}</SelectField></div><div className="border-y border-border-subtle py-4"><p className="text-xs text-text-muted">Calculated preview</p><p className="mt-2 font-heading text-2xl text-text-primary">{score} <span className="font-sans text-sm text-text-muted">/ 25 · {severity.toLowerCase()}</span></p></div><Field label="Rationale"><Textarea value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder="Explain this assessment" className="min-h-28" /></Field><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Save assessment</Button></SheetFooter></form></SheetContent></Sheet>
}

export function TreatmentSheet({ organizationId, risk, open, onOpenChange, onSaved }: { organizationId: string; risk: Risk; open: boolean; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const treatment = risk.treatment; const [strategy, setStrategy] = useState<TreatmentStrategy>(treatment?.strategy ?? "MITIGATE"); const [status, setStatus] = useState<TreatmentStatus>(treatment?.status ?? "NOT_STARTED"); const [plan, setPlan] = useState(treatment?.plan ?? ""); const [targetDate, setTargetDate] = useState(treatment?.targetDate?.slice(0, 10) ?? ""); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>(null)
  useEffect(() => { if (open) { setStrategy(treatment?.strategy ?? "MITIGATE"); setStatus(treatment?.status ?? "NOT_STARTED"); setPlan(treatment?.plan ?? ""); setTargetDate(treatment?.targetDate?.slice(0, 10) ?? ""); setError(null) } }, [open, treatment])
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await updateTreatment(organizationId, risk.id, { strategy, status, plan, ...(targetDate ? { targetDate: new Date(`${targetDate}T00:00:00.000Z`).toISOString() } : {}) }); onSaved(); onOpenChange(false) } catch (cause) { setError(cause) } finally { setSaving(false) } }
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full border-border-default bg-bg-elevated sm:max-w-[440px]"><SheetHeader className="border-b border-border-subtle px-6 py-5"><SheetTitle className="text-xl">Edit treatment</SheetTitle></SheetHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto px-6 py-6"><SelectField label="Strategy" value={strategy} onChange={(value) => setStrategy(value as TreatmentStrategy)}>{Object.entries(strategyLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField><SelectField label="Status" value={status} onChange={(value) => setStatus(value as TreatmentStatus)}>{Object.entries(treatmentStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField><Field label="Treatment plan"><Textarea value={plan} onChange={(event) => setPlan(event.target.value)} placeholder="Describe the planned response" className="min-h-32" /></Field><Field label="Target date"><div className="relative"><Input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /><CalendarDays className="pointer-events-none absolute right-3 top-2 size-4 text-text-muted" /></div></Field><FormError error={error} /></div><SheetFooter className="border-t border-border-subtle px-6 py-5 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : null}Save treatment</Button></SheetFooter></form></SheetContent></Sheet>
}
